trigger:
  branches:
    include:
    - master
    - devops-azure
  paths:
    include:
    - devops/cicd/arm-json/*

variables:
  - group: 'df-cicd'

# pool:
#   vmImage: ubuntu-latest
# steps:
#   - task: Bash@3
#     inputs:
#       targetType: 'inline'
#       script: |
#         ls
#         ls devops/cicd/arm-json/storage_accounts/
#         pwd

stages:  
  - stage: Storage_Hardcoded
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'df-cicd-service-connection'
            subscriptionId: '0b35426c-85f3-45e8-9f96-577a13b738d5'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'df-cicd'
            location: 'EAST US'
            templateLocation: 'Linked artifact'
            csmFile: 'devops/cicd/arm-json/storage_accounts/storage_accounts.json'
            overrideParameters: '-project df -environment cicd  -storageAccountName dfstoragecicd -bronzeLayer bronze-cicd -silverLayer silver-cicd -goldLayer gold-cicd'
            deploymentMode: 'Incremental'
            deploymentName: 'storage_accounts'

  - stage: Storage_Dynamic
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'devops/cicd/arm-json/storage_accounts/storage_accounts.json'
            overrideParameters: '-project $(PROJECT) -environment $(ENVIRONMENT)  -storageAccountName $(LAKEHOUSE_STORAGE_ACCOUNT) -bronzeLayer $(LAKEHOUSE_BRONZE_LAYER) -silverLayer $(LAKEHOUSE_SILVER_LAYER) -goldLayer $(LAKEHOUSE_GOLD_LAYER)'
            deploymentMode: 'Incremental'
            deploymentName: 'storage_accounts'

  - stage: Storage_Parallel
    dependsOn: []
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'devops/cicd/arm-json/storage_accounts/storage_accounts.json'
            overrideParameters: '-project $(PROJECT) -environment $(ENVIRONMENT)  -storageAccountName $(LAKEHOUSE_STORAGE_ACCOUNT) -bronzeLayer $(LAKEHOUSE_BRONZE_LAYER) -silverLayer $(LAKEHOUSE_SILVER_LAYER) -goldLayer $(LAKEHOUSE_GOLD_LAYER)'
            deploymentMode: 'Incremental'
            deploymentName: 'storage_accounts'
           